const data = [
  {
    userName: "Julian",
    userPictureSrc: "",
    userEmail: "Julian@web.de",
    userPhonenumber: "+1235794144",
    id: 1,
    adPictureSrc: "",
    adTitle: "Build an App",
    adDescription: "I can be a Hero in building an App for you.",
    adCosts: 99,
    category: "Technique",
    createdDate: "16.11.2022",
  },
  {
    userName: "Lisa",
    userPictureSrc: "",
    userEmail: "Lisa@web.de",
    userPhonenumber: "+1235794144",
    id: 2,
    adPictureSrc: "",
    adTitle: "Make awesome Pictures",
    adDescription: "I can be a Hero in making Pictures for you.",
    adCosts: 99,
    category: "Events",
    createdDate: "15.11.2022",
  },
  {
    userName: "Max",
    userPictureSrc: "",
    userEmail: "Max@web.de",
    userPhonenumber: "+1235794144",
    id: 3,
    adPictureSrc: "",
    adTitle: "DJing at your Event",
    adDescription: "I can be a Hero in Music for you.",
    adCosts: 99,
    category: "Events",
    createdDate: "14.11.2022",
  },
  {
    userName: "Clara",
    userPictureSrc: "",
    userEmail: "Clara@web.de",
    userPhonenumber: "+1235794144",
    id: 4,
    adPictureSrc: "",
    adTitle: "Help with your Homework",
    adDescription: "I can be a Hero in helping you with your kids homework.",
    adCosts: 99,
    category: "Education",
    createdDate: "13.11.2022",
  },
  {
    userName: "Kathrin",
    userPictureSrc: "",
    userEmail: "Kathrin@web.de",
    userPhonenumber: "+1235794144",
    id: 5,
    adPictureSrc: "",
    adTitle: "Cleanup your Home",
    adDescription: "I can be a Hero in cleaning up your Home.",
    adCosts: 99,
    category: "Home",
    createdDate: "12.11.2022",
  },
  {
    userName: "Heinz",
    userPictureSrc: "",
    userEmail: "Heinz@web.de",
    userPhonenumber: "+1235794144",
    id: 6,
    adPictureSrc: "",
    adTitle: "Cut the lawn",
    adDescription: "I can be a Hero in cut your lawn.",
    adCosts: 99,
    category: "Garden",
    createdDate: "11.11.2022",
  },
  {
    userName: "Carl",
    userPictureSrc: "",
    userEmail: "Carl@web.de",
    userPhonenumber: "+1235794144",
    id: 7,
    adPictureSrc: "",
    adTitle: "Change your Tires",
    adDescription: "I can be a Hero in changing the tires of your vehicles.",
    adCosts: 99,
    category: "Vehicles",
    createdDate: "10.11.2022",
  },
  {
    userName: "Irene",
    userPictureSrc: "",
    userEmail: "Irene@web.de",
    userPhonenumber: "+1235794144",
    id: 8,
    adPictureSrc: "",
    adTitle: "Baking Cookies for you",
    adDescription: "I can be a Hero in baking something Tasty for you.",
    adCosts: 99,
    category: "Cooking",
    createdDate: "9.11.2022",
  },
  {
    userName: "Jana",
    userPictureSrc: "",
    userEmail: "Jana@web.de",
    userPhonenumber: "+1235794144",
    id: 9,
    adPictureSrc: "",
    adTitle: "Babysitting your Kids",
    adDescription: "I can be a Hero in Babysitting for you.",
    adCosts: 99,
    category: "Care",
    createdDate: "8.11.2022",
  },
  {
    userName: "Hendrik",
    userPictureSrc: "",
    userEmail: "Hendrik@web.de",
    userPhonenumber: "+1235794144",
    id: 10,
    adPictureSrc: "",
    adTitle: "Setup your new Smartphone",
    adDescription: "I can be a Hero in setting up your new Smartphone for you.",
    adCosts: 99,
    category: "technique",
    createdDate: "7.11.2022",
  },
  {
    userName: "Carsten",
    userPictureSrc: "",
    userEmail: "Carsten@web.de",
    userPhonenumber: "+1235794144",
    id: 11,
    adPictureSrc: "",
    adTitle: "Help you with moving",
    adDescription: "I can be a Hero in helping you with your moving.",
    adCosts: 99,
    category: "Home",
    createdDate: "6.11.2022",
  },
  {
    userName: "Michael",
    userPictureSrc: "",
    userEmail: "Michael@web.de",
    userPhonenumber: "+1235794144",
    id: 12,
    adPictureSrc: "",
    adTitle: "Coach for dancing",
    adDescription: "I can be a Hero in helping you learn how to dance.",
    adCosts: 99,
    category: "Home",
    createdDate: "5.11.2022",
  },
];

export { data };
